import turtle


def vagon():
    martin = turtle.Pen()
    martin.reset()

    martin.color("magenta")
    martin.begin_fill()
    martin.forward(100)
    martin.left(90)
    martin.forward(50)
    martin.left(90)
    martin.forward(100)
    martin.left(90)
    martin.forward(50)
    martin.left(90)
    martin.end_fill()
    martin.up()
    martin.forward(20)
    martin.right(90)
    martin.forward(20)
    martin.down()
    martin.color("cyan")
    martin.begin_fill()
    martin.setheading(0)
    martin.circle(10)
    martin.end_fill()
    martin.up()
    martin.forward(60)
    martin.down()
    martin.color("cyan")
    martin.begin_fill()
    martin.setheading(0)
    martin.circle(10)
    martin.end_fill()
    martin.hideturtle()

    turtle.done()
